seed: 666
data_path: ./
train_batch_size: 32
eval_batch_size: 32
num_workers: 4
max_epochs: 20
train_epoch_length: 1000
eval_epoch_length: 1000
lr: 0.0001
use_amp: false
debug: false
model: resnet18
filename_prefix: training
n_saved: 2
save_every_iters: 1000
patience: 3
output_dir: ./logs
log_every_iters: 100

hydra:
  output_subdir: "."
  job:
    chdir: False

defaults:  
  - _self_  
  # - override hydra/hydra_logging: disabled
  # - override hydra/job_logging: disabled
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none
